// Dish Array
const dishes = [
  {
    dishName: 'PIZZA MARGARITA',
    dishDescription: 'Enjoy our very best home made pizza margerita. Tomato, basil and muzzarella',
    buttonDescription: 'add Margarita to cart',
    priceTag: 7.50,
    dishGroup: 'PIZZA',
    photoId: 'd01',
    photoSource1: '<a href="https://unsplash.com/@dabyki?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Nadezhda Filatova</a>',
    photoSource2: '<a href="https://unsplash.com/s/photos/pizza-and-pasta?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>',
  },
  {
    dishName: 'PEPPE PIZZA',
    dishDescription: 'Delicious Mozzarella, Parmesan, Tomato, Basil and Italian pepperoni.',
    buttonDescription: 'add Peppe Pizza to cart',
    priceTag: 8.50,
    dishGroup: 'PIZZA',
    photoId: 'd02',
    photoSource1: '<a href="https://unsplash.com/@shootdelicious?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Eiliv-Sonas Aceron</a>',
    photoSource2: '<a href="https://unsplash.com/s/photos/pizza-and-pasta?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>',
  },
  {
    dishName: 'PIZZA ANANA',
    dishDescription: '(Not in Naples!) Enjoy your flavours. Tomato, Pinnaple, Muzzarella and Jam!',
    buttonDescription: 'add Pizza Anana to cart',
    priceTag: 8.20,
    dishGroup: 'PIZZA',
    photoId: 'd03',
    photoSource1: '<a href="https://unsplash.com/@dabyki?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Nadezhda Filatova</a>',
    photoSource2: '<a href="https://unsplash.com/s/photos/pizza-and-pasta?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>',
  },
  {
    dishName: 'PIZZA FUNGUI',
    dishDescription: 'Mozzarella cheese, goat cheese, mashrooms and fresh herbs',
    buttonDescription: 'add Pizza Fungui to cart',
    priceTag: 9.10,
    dishGroup: 'PIZZA',
    photoId: 'd04',
    photoSource1: '<a href="https://unsplash.com/@pinarimsi?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Pinar Kucuk </a>',
    photoSource2: '<a href="https://unsplash.com/s/photos/pizza-and-pasta?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>',
  },
  {
    dishName: 'spagetti capresse',
    dishDescription: 'Fresh tomatoes, mozzarella and basil. Is the perfect combination. Enjoy!',
    buttonDescription: 'add capresse to cart',
    priceTag: 9.75,
    dishGroup: 'PASTA',
    photoId: 'd05',
    photoSource1: '<a href="https://unsplash.com/@foxfox?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Natalia Y </a>',
    photoSource2: '<a href="https://unsplash.com/s/photos/pizza-and-pasta?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>',
  },

  {
    dishName: 'pasta pescatora',
    dishDescription: 'Shrimp Tomato Spinach Pasta in Garlic Butter Sauce. Delicious!',
    buttonDescription: 'add pescatora to cart',
    priceTag: 11.20,
    dishGroup: 'PASTA',
    photoId: 'd06',
    photoSource1: '<a href="https://unsplash.com/@islandsandsunsets?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Olayinka Babalola </a>',
    photoSource2: '<a href="https://unsplash.com/s/photos/pizza-and-pasta?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>',
  },
  {
    dishName: 'Punch Tagliatelle',
    dishDescription: 'Tagliatelle with pumpkin, pancetta, sage and a little chilli for nice punch.!',
    buttonDescription: 'add Tagliatelle to cart',
    priceTag: 10.50,
    dishGroup: 'PASTA',
    photoId: 'd07',
    photoSource1: '<a href="https://unsplash.com/@ib1994?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Izzy Boscawen </a>',
    photoSource2: '<a href="https://unsplash.com/s/photos/pizza-and-pasta?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>',
  },

];

export default dishes;